apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-cso-install
  namespace: rhacm-policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-cso-install
        spec:
          severity: medium
          namespaceSelector:
            exclude:
            - '*'
            include:
            - 'openshift-operators'
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: container-security-operator
                  namespace: openshift-operators
                spec:
                  channel: quay-v3.3
                  installPlanApproval: Automatic
                  name: container-security-operator
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
                  startingCSV: container-security-operator.v3.3.1
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-binding-cso-install
  namespace: rhacm-policies
placementRef:
  name: dev-clusters
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-cso-install
  kind: Policy
  apiGroup: policy.open-cluster-management.io
